services:
  - type: web
    name: myaba
    runtime: node
    buildCommand: npm install && npx vite build
    startCommand: node server.js
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
