// ⬡B:MACE.phase0:UTILS:markdown_shared:20260405⬡
// Markdown rendering — extracted from MyABA.jsx
// Used by Bubble component and multiple views for rendering ABA responses

import React from "react";
import { Copy } from "lucide-react";

export function renderInline(t){const p=[];let r=t;const re=/\*\*(.+?)\*\*/g;let m,last=0,k=0;while((m=re.exec(r))!==null){if(m.index>last)p.push(r.slice(last,m.index));p.push(<strong key={`b${k++}`} style={{color:"rgba(255,255,255,.95)"}}>{m[1]}</strong>);last=m.index+m[0].length}if(last<r.length)p.push(r.slice(last));return p.length>0?p:t}

export function renderMd(text){if(!text)return null;let c=text.replace(/^\[(warm|firm|thoughtful|gentle|encouraging|excited|celebratory|annoyed)\]\s*/i,"");const lines=c.split("\n"),blocks=[];let i=0;while(i<lines.length){const ln=lines[i];if(ln.startsWith("```")){const lang=ln.slice(3).trim();const code=[];i++;while(i<lines.length&&!lines[i].startsWith("```")){code.push(lines[i]);i++}i++;const codeText=code.join("\n");blocks.push(<div key={`c${blocks.length}`} style={{position:"relative",margin:"8px 0"}}><div style={{position:"absolute",top:0,left:0,right:0,height:28,background:"rgba(139,92,246,.12)",borderRadius:"12px 12px 0 0",display:"flex",alignItems:"center",justifyContent:"space-between",padding:"0 12px"}}><span style={{color:"rgba(139,92,246,.7)",fontSize:10,fontWeight:600,textTransform:"uppercase"}}>{lang||"code"}</span><button onClick={()=>navigator.clipboard.writeText(codeText)} style={{background:"none",border:"none",color:"rgba(255,255,255,.4)",cursor:"pointer",fontSize:9,padding:"2px 6px",borderRadius:4}}><Copy size={10}/></button></div><pre style={{background:"rgba(0,0,0,.5)",border:"1px solid rgba(139,92,246,.15)",borderRadius:12,padding:"36px 14px 12px",margin:0,overflowX:"auto",fontSize:12,lineHeight:1.6,fontFamily:"'SF Mono',Menlo,monospace"}}><code style={{color:"rgba(134,239,172,.85)"}}>{codeText}</code></pre></div>);continue}if(ln.startsWith("### "))blocks.push(<p key={`h${i}`} style={{fontWeight:600,color:"rgba(255,255,255,.8)",fontSize:13,margin:"10px 0 4px"}}>{ln.slice(4)}</p>);else if(ln.startsWith("## "))blocks.push(<p key={`h${i}`} style={{fontWeight:700,color:"rgba(255,255,255,.9)",fontSize:14,margin:"12px 0 4px"}}>{ln.slice(3)}</p>);else if(ln.startsWith("- ")||ln.startsWith("* "))blocks.push(<p key={`li${i}`} style={{paddingLeft:14,color:"rgba(255,255,255,.75)",fontSize:13,margin:"3px 0",position:"relative"}}><span style={{position:"absolute",left:0,color:"rgba(139,92,246,.6)"}}>•</span>{renderInline(ln.slice(2))}</p>);else if(ln.trim())blocks.push(<p key={`p${i}`} style={{color:"rgba(255,255,255,.85)",fontSize:13,margin:"4px 0",lineHeight:1.6}}>{renderInline(ln)}</p>);i++}return blocks}
